### ISSUE TITLE
using use_frameworks! in Podfile breaks IOS build (since 1.0.0) (Missing header file) 

### ISSUE THREAD

**Issue by knaeckeKami** [AmolGangadhare/flutter_barcode_scanner#89]
Hi, first of all thanks for the work you put into this plugin!

**Describe the bug**
Since the upgrade to 1.0.0, I cannot build my app anymore or IOS.
It fails with

```
.../flutter_barcode_scanner/ios/Classes/FlutterBarcodeScannerPlugin.m:2:9: fatal error:
    'flutter_barcode_scanner-Swift.h' file not found
    #import <flutter_barcode_scanner-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```
It seems that the use of use_frameworks! in the Podfile causes this. Unfortunately, this is required by other plugins that I use (e.g. workmanager).

**To Reproduce**
1. use the example app
2. add use_frameworks! to the Podfile again, as it was before the upgrade to 1.0
3. build the app

**Expected behavior**
The app should build on ios even with use_frameworks! set.

**Comment by Xgamefactory** [comment]
same here. searching for alternative mainteden plugin.

**Comment by knaeckeKami** [comment]
@Xgamefactory Until my PR is merged, you can use my fork at
git: https://github.com/knaeckeKami/flutter_barcode_scanner.git

**Comment by Xgamefactory** [comment]
> @Xgamefactory Until my PR is merged, you can use my fork at
> git: https://github.com/knaeckeKami/flutter_barcode_scanner.git

thanks !

**Comment by lookfirst** [comment]
the fix is simple, but once I built it, the flash icon wasn't set properly... might as well just stick with the 0.7.1 version.

**Comment by nicolasvahidzein** [comment]
I'm having the same trouble, when can we expect a new version please?

**Comment by lookfirst** [comment]
@nicolasvahidzein Just hold on 0.7.1. You don't want the latest version as it has other issues.
