### PR TITLE
allow plugin to be used in projects with use_frameworks!

### LINKED ISSUE #89: using use_frameworks! in Podfile breaks IOS build (since 1.0.0) (Missing header file)
Hi, first of all thanks for the work you put into this plugin!

**Describe the bug**
Since the upgrade to 1.0.0, I cannot build my app anymore or IOS.
It fails with

```
.../flutter_barcode_scanner/ios/Classes/FlutterBarcodeScannerPlugin.m:2:9: fatal error:
    'flutter_barcode_scanner-Swift.h' file not found
    #import <flutter_barcode_scanner-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.
```
It seems that the use of use_frameworks! in the Podfile causes this. Unfortunately, this is required by other plugins that I use (e.g. workmanager).

**To Reproduce**
1. use the example app
2. add use_frameworks! to the Podfile again, as it was before the upgrade to 1.0
3. build the app

**Expected behavior**
The app should build on ios even with use_frameworks! set.

### PR DESCRIPTION
**Pull request by knaeckeKami**
Reverts some of the changes made to the ios build system in 1.0.0, which broke projects that use use_frameworks!

fixes #89

### CODE REVIEW

File: example/ios/Podfile [hunk 1]
```diff
@@ -33,7 +33,7 @@ def parse_KV_file(file, separator='=')
 end
 
 target 'Runner' do
-#  use_frameworks!
+  use_frameworks!
```
Comment (AmolGangadhare) [inline example/ios/Podfile:36]: we need to keep only 'use_frameworks!' please remove 'use_modular_headers!'

**Comment by AmolGangadhare** [comment]
Thanks for your contribution to the plugin
